/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fwc_log_TelLog */

#ifndef _Included_com_fwc_log_TelLog
#define _Included_com_fwc_log_TelLog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fwc_log_TelLog
 * Method:    nativeFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fwc_log_TelLog_nativeFree
  (JNIEnv *, jobject);

/*
 * Class:     com_fwc_log_TelLog
 * Method:    nativeConnectServer
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_fwc_log_TelLog_nativeConnectServer
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_fwc_log_TelLog
 * Method:    sendData
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_fwc_log_TelLog_sendData
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_fwc_log_TelLog
 * Method:    sendDataByte
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_fwc_log_TelLog_sendDataByte
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_fwc_log_TelLog
 * Method:    isConnect
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_fwc_log_TelLog_isConnect
  (JNIEnv *, jobject);

/*
 * Class:     com_fwc_log_TelLog
 * Method:    disConnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fwc_log_TelLog_disConnect
  (JNIEnv *, jobject);

/*
 * Class:     com_fwc_log_TelLog
 * Method:    connect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fwc_log_TelLog_connect
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
